all:
  children:
    webservers:
      hosts:
        apache.open-bio.org:
    listservers:
      hosts:
        mailman.open-bio.org:
    bugtrackers:
    buildbots:
    aws:
      children:
        webservers:
        listservers:
        bugtrackers:
        buildbots:
