---
- name: perform yum update followed by reboot
  hosts: aws
  become: yes
  remote_user: ec2-user

  roles:
    - role: update
    - role: GROG.reboot
      reboot_wait: yes
      reboot_wait_delay: 60

