---
- name: perform yum update followed by reboot
  hosts: aws
  become: yes
#  debugger: on_failed

  roles:
    - role: stafwag.package_update
    - role: GROG.reboot
      reboot_wait: yes
      reboot_wait_delay: 60

